### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by dargmuesli** [flipdot/adventskranz#2]
I am wondering why there is a special coloring needed for the second LED strip. It needs
`uint32_t green2 = strip.Color(0, 0, 6);` instead of
`uint32_t green = strip.Color(0, 4, 0);` which is basically dark blue and the flame colors are defined as
`flame[i] = strip.Color(ran, 0, ran/2);` instead of
`flame[i] = strip.Color(ran, ran/2, 0);` accordingly.

Why is that? Would you please add a comment explaining this?
Thanks in advance.

**Comment by malled2002** [comment]
The second stripe has a different byte order for RGB bytes. So this is just a dirty fix. Sry

**Comment by dargmuesli** [comment]
Ok, could you please explain that difference or link a documentation for that?

**Comment by malled2002** [comment]
The rgb byte order is described in the datasheets [1] [2]. You can compare the "Composition of 24bit data" section (Page 4/5)

[1] https://cdn-shop.adafruit.com/datasheets/WS2811.pdf
[2] https://cdn-shop.adafruit.com/datasheets/WS2812B.pdf

**Comment by dargmuesli** [comment]
Ok, now I get it. I'll later add a comment to my existing pull request.

Still one question: can we equalize the first two variables for green to be defined as
`strip.Color(0, 0, 5)` and
`strip.Color(0, 5, 0)`? Or is this part of the *fix* you spoke about?
